env:
  browser: true
  es2021: true
extends:
- react-app
- react-app/jest
- airbnb
- plugin:prettier/recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {
  "react/prop-types": 0,
  "react/jsx-filename-extension": 0,
  "react/destructuring-assignment": 0,
  "react/static-property-placement": 0,
  "jsx-a11y/label-has-associated-control": [
    2,
    {
      "assert": "either"
    }
  ],
  "no-console": "off",
  "no-alert": "off"
}
