# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger: none

schedules:
- cron: '0 17 * * *'
  displayName: Daily build
  branches:
    include:
    - release

stages:
- stage: Build
  displayName: Build stage

  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest

    steps:
    - task: NodeTool@0
      inputs:
        versionSource: 'spec'
        versionSpec: '18.x'
        checkLatest: true
      displayName: 'Install Node.js'

    - script: |
          cd ./frontend
          npm ci --omit=dev
          npm run build
      displayName: 'npm install and build'

    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(build.sourcesdirectory)/frontend/build'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        replaceExistingArchive: true

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: succeeded()

  jobs:
  - job: Deploy
    displayName: Deploy frontend
    pool:
      vmImage: ubuntu-latest

    steps:
    - download: current
      artifact: drop

    - task: AzureRmWebAppDeployment@4
      displayName: 'Azure Web App Deploy: tsw-web'
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'TSW-WEB-APP-DJANGO'
        appType: 'webAppLinux'
        WebAppName: 'tsw-web'
        packageForLinux: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'
        RuntimeStack: 'NODE|18-lts'
        StartupCommand: 'pm2 serve /home/site/wwwroot --spa --no-daemon'
