# Generated by Django 4.0.8 on 2023-10-03 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('texturedar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='next_step',
            field=models.ForeignKey(db_column='next_step_name', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_next_related_steps', to='texturedar.step', to_field='name'),
        ),
        migrations.AlterField(
            model_name='step',
            name='previous_step',
            field=models.ForeignKey(db_column='previous_step_name', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_prev_related_steps', to='texturedar.step', to_field='name'),
        ),
    ]
