# Generated by Django 4.0.8 on 2024-01-24 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('texturedar', '0002_alter_step_next_step_alter_step_previous_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='fail',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='finalproductsku',
            name='replaced',
            field=models.ForeignKey(db_column='replaced_name', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replaced_skus', to='texturedar.finalproductsku', to_field='name'),
        ),
        migrations.AddField(
            model_name='opticalcoatsku',
            name='replaced',
            field=models.ForeignKey(db_column='replaced_name', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replaced_skus', to='texturedar.opticalcoatsku', to_field='name'),
        ),
        migrations.AddField(
            model_name='rawmaterialsku',
            name='replaced',
            field=models.ForeignKey(db_column='replaced_name', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replaced_skus', to='texturedar.rawmaterialsku', to_field='name'),
        ),
        migrations.AddField(
            model_name='vendorsku',
            name='replaced',
            field=models.ForeignKey(db_column='replaced_name', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replaced_skus', to='texturedar.vendorsku', to_field='name'),
        ),
    ]
