# Generated by Django 4.0.8 on 2024-01-25 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('texturedar', '0003_fail_active_finalproductsku_replaced_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='batch_content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_batch_items', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='part',
            name='shipment_content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_shipped_items', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='part',
            name='step_content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_step_items', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='tarbatch',
            name='step_content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_step_items', to='contenttypes.contenttype'),
        ),
    ]
