# Generated by Django 4.0.8 on 2024-01-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texturedar', '0004_alter_part_batch_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarbatch',
            name='order_no',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
