# Generated by Django 4.0.8 on 2024-02-01 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texturedar', '0005_alter_tarbatch_order_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarbatch',
            name='batch_type',
            field=models.CharField(choices=[('PRODUCTION', 'PRODUCTION'), ('DEVELOPMENT', 'DEVELOPMENT'), ('TEST', 'TEST'), ('CUSTOM', 'CUSTOM')], default='PRODUCTION', max_length=25),
        ),
    ]
