# Generated by Django 4.0.8 on 2023-10-12 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moe', '0003_project_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='invoice',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='invoiced',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='purchase_order',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='quote',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='quote_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='quoted',
            field=models.DateField(null=True),
        ),
    ]
