# Generated by Django 4.0.8 on 2024-01-25 15:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reticle', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GeneralNote',
            new_name='OldGeneralNote',
        ),
        migrations.RenameModel(
            old_name='MaintenanceRequest',
            new_name='OldMaintenanceRequest',
        ),
    ]
