# Generated by Django 4.0.8 on 2024-01-25 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reticle', '0002_rename_generalnote_oldgeneralnote_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oldmaintenancerequest',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='OldGeneralNote',
        ),
        migrations.DeleteModel(
            name='OldMaintenanceRequest',
        ),
    ]
