# Generated by Django 4.0.8 on 2024-01-25 16:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reticle', '0005_sheetbatch_dicebatch_coatbatch'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Plate',
            new_name='OldPlate',
        ),
    ]
