# Generated by Django 4.0.8 on 2024-01-25 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reticle', '0007_rename_part_oldpart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fail',
            new_name='OldFail',
        ),
        migrations.RenameModel(
            old_name='Step',
            new_name='OldStep',
        ),
    ]
