# Generated by Django 4.0.8 on 2024-01-26 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('reticle', '0009_fail_step'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('notes', models.CharField(max_length=250, null=True)),
                ('batch_object_id', models.PositiveIntegerField(null=True)),
                ('shipment_object_id', models.PositiveIntegerField(null=True)),
                ('step_object_id', models.PositiveIntegerField()),
                ('serial', models.CharField(max_length=50, null=True)),
                ('index', models.PositiveIntegerField()),
                ('fail1_object_id', models.PositiveIntegerField(null=True)),
                ('fail2_object_id', models.PositiveIntegerField(null=True)),
                ('fail3_object_id', models.PositiveIntegerField(null=True)),
                ('high_grade', models.BooleanField(default=False)),
                ('coated', models.DateTimeField(null=True)),
                ('wip1_in', models.DateTimeField(null=True)),
                ('wip1_out', models.DateTimeField(null=True)),
                ('sheet_index', models.IntegerField(null=True)),
                ('exposed', models.DateTimeField(null=True)),
                ('etched', models.DateTimeField(null=True)),
                ('etch_time', models.FloatField(default='0.0', null=True)),
                ('recycled', models.BooleanField(default=False)),
                ('recycled_in', models.DateTimeField(null=True)),
                ('recycled_out', models.DateTimeField(null=True)),
                ('sheet_batch_object_id', models.PositiveIntegerField(null=True)),
                ('scrapped', models.BooleanField(default=False)),
                ('batch_content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_batch_items', to='contenttypes.contenttype')),
                ('fail1_content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_fail1_parts', to='contenttypes.contenttype')),
                ('fail2_content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_fail2_parts', to='contenttypes.contenttype')),
                ('fail3_content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_fail3_parts', to='contenttypes.contenttype')),
                ('pm_sku', models.ForeignKey(db_column='pm_sku_name', null=True, on_delete=django.db.models.deletion.PROTECT, to='reticle.photomasksku', to_field='name')),
                ('rm_sku', models.ForeignKey(db_column='rm_sku_name', null=True, on_delete=django.db.models.deletion.PROTECT, to='reticle.rawmaterialsku', to_field='name')),
                ('sheet_batch_content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_sheet_batch_items', to='contenttypes.contenttype')),
                ('shipment_content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_shipped_items', to='contenttypes.contenttype')),
                ('step_content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_step_items', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
