# Generated by Django 4.0.8 on 2024-01-26 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reticle', '0010_plate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oldpart',
            name='plate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_part_set', to='reticle.oldplate'),
        ),
    ]
