# Generated by Django 4.0.8 on 2024-01-26 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reticle', '0012_part'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='code',
        ),
    ]
