# Generated by Django 4.0.8 on 2024-01-26 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reticle', '0013_remove_productcategory_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicebatch',
            name='plate_qty',
            field=models.IntegerField(null=True),
        ),
    ]
