# Generated by Django 4.0.8 on 2024-01-29 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reticle', '0014_dicebatch_plate_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plate',
            name='sheet_index',
        ),
    ]
