# Generated by Django 4.0.8 on 2024-01-29 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reticle', '0015_remove_plate_sheet_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterialsku',
            name='vendor_sku',
            field=models.ForeignKey(db_column='vendor_sku_name', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='related_rmskus', to='reticle.vendorsku', to_field='name'),
        ),
    ]
