# Generated by Django 4.0.8 on 2024-01-29 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reticle', '0016_alter_rawmaterialsku_vendor_sku'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fail',
        ),
    ]
