# Generated by Django 4.0.8 on 2024-01-29 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reticle', '0017_delete_fail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OldFail',
            new_name='Fail',
        ),
    ]
