# Generated by Django 4.0.8 on 2024-02-01 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reticle', '0020_alter_plate_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plate',
            name='serial',
            field=models.IntegerField(null=True),
        ),
    ]
