# Generated by Django 4.0.8 on 2024-02-02 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reticle', '0022_alter_coatbatch_batch_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plate',
            name='wip2_in',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='plate',
            name='wip2_out',
            field=models.DateTimeField(null=True),
        ),
    ]
