# Generated by Django 4.0.8 on 2024-02-14 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reticle', '0024_remove_coat_skus_rm_sku_remove_dice_batch_created_by_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Warehouse',
        ),
    ]
