# Generated by Django 4.0.8 on 2024-02-02 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalnote',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
