# Generated by Django 4.0.8 on 2023-10-12 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moecustomerpayment',
            name='project',
        ),
        migrations.RemoveField(
            model_name='moecustomerproject',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='moecustomerproject',
            name='status',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='sku_content_type',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='warehouse',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='MoeCustomerPayment',
        ),
        migrations.DeleteModel(
            name='MoeCustomerProject',
        ),
        migrations.DeleteModel(
            name='Shipment',
        ),
        migrations.DeleteModel(
            name='Warehouse',
        ),
    ]
