# Generated by Django 4.0.8 on 2023-10-13 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0003_requeststatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='status',
            field=models.ForeignKey(db_column='status_code', default='OPEN', on_delete=django.db.models.deletion.PROTECT, related_name='status_requests', to='purchasing.requeststatus', to_field='code'),
        ),
    ]
