# Generated by Django 4.0.8 on 2023-10-19 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0004_purchaserequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitem',
            name='approved',
            field=models.ForeignKey(default='PEND', on_delete=django.db.models.deletion.PROTECT, related_name='approved_items', to='purchasing.approvalstatus', to_field='code'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='authorized',
            field=models.ForeignKey(default='PEND', on_delete=django.db.models.deletion.PROTECT, related_name='authorized_items', to='purchasing.approvalstatus', to_field='code'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='status',
            field=models.ForeignKey(default='REQ', on_delete=django.db.models.deletion.PROTECT, related_name='requested_items', to='purchasing.itemstatus', to_field='code'),
        ),
    ]
