# Generated by Django 4.0.8 on 2023-10-19 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0005_alter_purchaseitem_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitem',
            name='status',
            field=models.ForeignKey(default='CREATE', on_delete=django.db.models.deletion.PROTECT, related_name='requested_items', to='purchasing.itemstatus', to_field='code'),
        ),
    ]
