# Generated by Django 4.0.8 on 2023-10-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0006_alter_purchaseitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='est_delivery',
            field=models.DateField(null=True),
        ),
    ]
