"""
Django settings for tsw_web project.

Generated by 'django-admin startproject' using Django 3.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

import os
from .shared import *


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Declare list of usernames for permissions of various views
AUTHORIZATION_ALLOWED_USERS = ['afisher', 'rkennedy', 'jwilliamson', 'rpriore', 'hsmith', 'dcdavis']
TRANSACTION_ALLOWED_USERS = ['hsmith', 'charvell', 'afisher', 'dcdavis']
APPROVAL_ALLOWED_USERS = ['jwilliamson', 'rpriore', 'hsmith', 'dcdavis']

# SECURITY WARNING: don't run with with wildcard in production!
ALLOWED_HOSTS = ['*']

# Database Definitions
DATABASES = {
    'default': {
        'ENGINE': 'mssql',
        'NAME': 'tsw_web_dev',
        'USER': os.environ.get('DB_USER'),
        'PASSWORD': os.environ.get('DB_PASSWORD'),
        'HOST': 'ar-database-thorlabs.database.windows.net',
        'PORT': '1433',
        'OPTIONS':{
            'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
}

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "level": "INFO",
            "class": "logging.StreamHandler",
        },
        "file_json": {
            "level": "WARNING",
            "class": "logging.handlers.WatchedFileHandler",
            "filename": 'error_log.json'
        },
        "file_common": {
            "level": "INFO",
            "class": "logging.handlers.WatchedFileHandler",
            "filename": 'requests_common.log'
        }
    },
    "loggers": {
        "json-logger": {
            "handlers": ["file_json"],
            "level": "INFO",
            "propagate": False
        },
        "common-logger": {
            "handlers": ["file_common"],
            "level": "INFO",
            "propagate": False
        },
    }
}

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR.parent,'static_collected')

MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(BASE_DIR.parent,'media_root')

CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',
]

FORECAST_MODEL_HOST = "http://127.0.0.1:8501/v1/models/purchase_lstm_forecast_model:predict"
