"""
Django settings for tsw_web project.

Generated by 'django-admin startproject' using Django 3.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

import os
from .shared import *

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

# Declare list of usernames for permissions of various views
AUTHORIZATION_ALLOWED_USERS = ['afisher', 'rkennedy', 'jwilliamson', 'rpriore', 'hsmith']
TRANSACTION_ALLOWED_USERS = ['hsmith', 'charvell', 'afisher']
APPROVAL_ALLOWED_USERS = ['jwilliamson', 'rpriore', 'hsmith']

# allowed hosts, use environment variable
ALLOWED_HOSTS = [os.environ.get('WEBSITE_HOSTNAME', '*')]

# Database Definitions
DATABASES = {
    'default': {
        'ENGINE': 'mssql',
        'NAME': 'tsw_web_production',
        'USER': os.environ.get('DB_USER'),
        'PASSWORD': os.environ.get('DB_PASSWORD'),
        'HOST': 'ar-database-thorlabs.database.windows.net',
        'PORT': '1433',
        'OPTIONS':{
            'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
}

SECURE_HSTS_SECONDS = 60

SECURE_HSTS_INCLUDE_SUBDOMAINS = True

SECURE_HSTS_PRELOAD = True

#SECURE_SSL_REDIRECT = True

SESSION_COOKIE_SECURE = True

SECURE_REFERRER_POLICY = 'same-origin'

CSRF_COOKIE_SECURE = True

# link to storage classes in AzureStorage module
DEFAULT_FILE_STORAGE = 'tsw_web.settings.backend.AzureMediaStorage'
STATICFILES_STORAGE  = 'tsw_web.settings.backend.AzureStaticStorage'

# AZURE specific custom settings, these are not for use by django
AZURE_STORAGE_KEY = os.environ.get('AZURE_STORAGE_KEY')
AZURE_ACCOUNT_NAME = os.environ.get('AZURE_ACCOUNT_NAME', 'tsw')
AZURE_MEDIA_CONTAINER = os.environ.get('AZURE_MEDIA_CONTAINER', 'media')
AZURE_STATIC_CONTAINER = os.environ.get('AZURE_STATIC_CONTAINER', 'static')
# AZURE_CUSTOM_DOMAIN = f'{AZURE_ACCOUNT_NAME}.azureedge.net'  # CDN URL
AZURE_CUSTOM_DOMAIN = f'{AZURE_ACCOUNT_NAME}.blob.core.windows.net'  # Files URL

# set up static/media storage using AZURE settings
STATIC_URL = f'https://{AZURE_CUSTOM_DOMAIN}/{AZURE_STATIC_CONTAINER}/'
MEDIA_URL = f'https://{AZURE_CUSTOM_DOMAIN}/{AZURE_MEDIA_CONTAINER}/'

CORS_ALLOWED_ORIGINS =[
    'https://tsw-web.azurewebsites.net'
]

CSRF_TRUSTED_ORIGINS =[
    'https://tsw-web.azurewebsites.net'
]

FORECAST_MODEL_HOST = "http://10.75.25.20:8501/v1/models/purchase_lstm_forecast_model:predict"

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "filters": {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse'
        }
    },
    "handlers": {
        "file_json": {
            "level": "WARNING",
            "class": "logging.handlers.WatchedFileHandler",
            "filename": '/home/site/wwwroot/error_log.json'
        },
        "file_common": {
            "level": "INFO",
            "class": "logging.handlers.WatchedFileHandler",
            "filename": '/home/site/wwwroot/requests_common.log'
        }
    },
    "loggers": {
        "json-logger": {
            "handlers": ["file_json"],
            "level": "INFO",
            "propagate": False
        },
        "common-logger": {
            "handlers": ["file_common"],
            "level": "INFO",
            "propagate": False
        },
    }
}
