# Generated by Django 4.0.8 on 2023-10-12 00:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='user',
            field=models.ForeignKey(db_column='user_name', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='related_users', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
