# Generated by Django 4.0.8 on 2024-01-29 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0002_alter_shipment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='final',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
