# Generated by Django 4.0.8 on 2023-10-11 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shaping', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='service',
            new_name='service_code',
        ),
    ]
