# Generated by Django 4.0.8 on 2024-02-05 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shaping', '0002_rename_service_service_service_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
